### ISSUE TITLE
gPathToSuggestedInteractionProfileBinding should be keyed from InstanceInfo because it's a map with key XrPath, which is Instance-specific.

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/OpenXR-OverlayLayer#20]
It's a global in the generated source, emitted in generate.py around line 817.

**Comment by jzulauf-lunarg** [comment]
@bradgrantham-lunarg  -- this variable is defined but otherwise unreferenced.  Is this a stale issue?

**Comment by bradgrantham-lunarg** [comment]
I think so.  Generate.py says "# left here as breadcrumbs - xrSuggestInteractionProfileBindings is completely hand-written" before a snippet containing "gPathToSuggestedInteractionProfileBinding", so I'm guessing I rewrote the hooked SuggestInteractionProfileBindings and didn't use gPathToSuggestedInteractionProfileBinding in the rewrite.  Issue may have been resolved but not closed.
