### ISSUE TITLE
Release gives openxr.lib error

### ISSUE THREAD

**Issue by TomGitHub9** [LunarG/OpenXR-OverlayLayer#29]
Hello,

I use VS2022 and latest SDK's.
I can build the app in debug mode without error, however when I switch to release I get an error that openxr.lib is not found.
I need the release version, or otherwise I cannot use the app to test on a separate system.
The XR_EXTX_overlay is build, but the problem seems to sit in the OverlaySample.

My goal is to create a simple form as an OpenXR overlay, and wanted to use this example

Your support is appreciated!

**Comment by bradgrantham-lunarg** [comment]
@TomGitHub9 Can you try out the change listed in #28?

**Comment by TomGitHub9** [comment]
Hi Brad,

 

Thank you for the reply.

 

Indeed this was the same issue, and now I was able to build the release version!

 

I still have some problems to get it all work based upon the instruction.

1.	I made the xr_extx_overlay.dll implicit in the register -> okay
2.	I started the hello.xr.exe -g -D3D11  -> without the register set (1) the blocks are visible in WMR VR, but with the register set (1) the environment of WMR is not made active
3.	I tried to make the “set XR_ENABLE_API_LAYERS=xr_extx_overlay” and “set XR_API_LAYER_PATH=<<Directory of xr_extx_overlay.dll>>” via the CMD.exe

 

The overlay is seen in the OpenXR explorer, so is set correctly.

What am I doing wrong?

 

Thank you very much in advance!

 

 

 

 

Van: bradgrantham-lunarg ***@***.***> 
Verzonden: donderdag 12 januari 2023 01:48
Aan: LunarG/OpenXR-OverlayLayer ***@***.***>
CC: TomGitHub9 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [LunarG/OpenXR-OverlayLayer] Release gives openxr.lib error (Issue #29)

 

@TomGitHub9 <https://github.com/TomGitHub9>  Can you try out the change listed in #28 <https://github.com/LunarG/OpenXR-OverlayLayer/pull/28> ?
