### ISSUE TITLE
implement overlay interaction scenarios in overlay_remote

### ISSUE THREAD

**Issue by michaelplutovr** [LunarG/OpenXR-OverlayLayer#8]
Include an interaction mode in which a widget image is displayed in the
the top-left 1/16th (left 1⁄4 by top 1⁄4) of the overlay composition layers and
is highlighted when the grip direction intersects the widget image.

**Comment by bradgrantham-lunarg** [comment]
Implemented variant in which background color of entire image changes on grip direction and also on select pressed.
